#!/bin/bash
BASE_DIR=$(dirname "$(readlink -f "$0")")

while getopts 'i:o:h' flag
do
    case "$flag" in
        i) INFILE="$OPTARG"
           ;;
        o) OUTFILE="$OPTARG"
           ;;
        h) echo "Usage: smlformat [-i inputfile] [-o outputfile]"
           echo "  -i infile    read code from file instead of stdin"
           echo "  -o outfile   write formatted code to file instead of stdout"
           echo "  -h           print this help message"
           exit 0
           ;;
        ?) echo "Usage: smlformat [-i inputfile] [-o outputfile]"
        ;;
    esac
done

INPUT=$(mktemp /tmp/smlformat.XXXXXX)
OUTPUT=$(mktemp /tmp/smlformat.XXXXXX)
trap 'rm -f -- "$INPUT"' INT TERM HUP EXIT
trap 'rm -f -- "$OUTPUT"' INT TERM HUP EXIT

if [ "$INFILE" ]
then
    cat $INFILE > $INPUT
else
    cat <&0 > $INPUT
fi

echo "SmlFormat.formatToFile \"$INPUT\" \"$OUTPUT\";" | sml -m "$BASE_DIR/sources.cm" > /dev/null

if  [ ! -s $OUTPUT ]
then
    cat $INPUT > $OUTPUT
fi

if [ "$OUTFILE" ]
then
    cat $OUTPUT > $OUTFILE
else
    cat $OUTPUT
fi

rm "$INPUT"
rm "$OUTPUT"
